version: '3.8'

services:
  web:
    image: node:14
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    environment:
      NODE_ENV: production
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
